### ISSUE TITLE
בעיה באמצע הורדה

### ISSUE THREAD

**Issue by KnaperYaden** [MusiCode1/jewish-music.fm#4]
לפעמים יש לי בעיה באמצע תהליך ההורדה.

התיבה הקופצת מציגה שוב ושוב הורדת אותה חתיכה והיא אף פעם לא נגמרת.

בקונסולה אני רואה את השגיאה הזו (ורואה אחרי זה 64 פעמים את אותו הדבר):
![image](https://user-images.githubusercontent.com/87161728/159915174-d2f9b977-4f00-49d5-9451-9950097bee19.png)

האם ניתן להוסיף סוג של טיפול בשגיאות כאשר השגיאה הזו מתרחשת?

(העברית מתורגמת על ידי גוגל... תודיע לי אם אתה מבין אנגלית או יידיש...)

**Comment by KnaperYaden** [comment]
עוד שגיאה אחרת שגורם להפסקת ההורדה.

(השגיאה כנראה מתחלת כשקובץ יחידה אינו זמין - ובאמת אותו קובץ אינו עובד גם על האתר עצמו.)

אבל למה שלא תציין בתיבה הקופצת שקובץ זה לא מוריד ולהמשיך בקובץ הבא?

![image](https://user-images.githubusercontent.com/87161728/159951495-a939cf3c-a706-48eb-99cf-6a9695676bad.png)
![image](https://user-images.githubusercontent.com/87161728/159951506-cfd2af7f-6fb6-494b-ae76-8638cbc3b3b4.png)

**Comment by ashuvax** [comment]
#6

**Comment by KnaperYaden** [comment]
תודה @ashuvax

(תיקן כאן https://github.com/MusiCode1/jewish-music.fm/blob/master/public/build/bundle.js, הוראות השימוש ב https://github.com/MusiCode1/jewish-music.fm/blob/master/README.md לא עידכן
